package com.aishatmoshood.weeksixmain.dao.impl;

import com.aishatmoshood.weeksixmain.dao.PostDao;
import com.aishatmoshood.weeksixmain.dto.PostDto;
import com.aishatmoshood.weeksixmain.models.Post;
import com.aishatmoshood.weeksixmain.models.User;
import com.aishatmoshood.weeksixmain.util.DatabaseConnection;

import java.sql.*;

public class PostDaoImpl implements PostDao {

    @Override
    public Post createPost(PostDto postDto, User user) {
        final String userInsertSql = "insert into post (user_id, post_title, post_body, created_at) " + "values (?,?,?,?)";

        Post savedPost = null;

        try (Connection connection = DatabaseConnection.INSTANCE.getDataSource().getConnection()) {

            PreparedStatement statement = connection.prepareStatement(userInsertSql, Statement.RETURN_GENERATED_KEYS);

            statement.setInt(1, new UserDaoImpl().getAUser(user).getId());
            statement.setString(2, postDto.getPost_title());
            statement.setString(3, postDto.getPost_body());
            statement.setObject(4, postDto.getCreatedAt());

            int result = statement.executeUpdate();

            final ResultSet keysResultSet = statement.getGeneratedKeys();

            keysResultSet.next();

            final int autogeneratedId = keysResultSet.getInt(1);

            savedPost = result == 1? new Post(autogeneratedId,user.getId(),postDto.getPost_title(),postDto.getPost_body(),postDto.getCreatedAt()) : null;

            System.out.println("Result: " + result);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return savedPost;
    }

    @Override
    public  boolean isEmailExist(String email){
        final String SELECT_USER_BY_EMAIL = "select * from user where email = ?";

        boolean status = false;
//        User user = new User();

        try(Connection connection = DatabaseConnection.INSTANCE.getDataSource().getConnection(); ){
            PreparedStatement statement = connection.prepareStatement(SELECT_USER_BY_EMAIL);

            statement.setString(1, email);

            ResultSet resultSet = statement.executeQuery();
            System.out.println(resultSet);
            status = resultSet.next();
        } catch (Exception ex){
            ex.printStackTrace();
        }
//        return status;
        return false;
    }
}
